// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq4vy878tlAj2T9DyMCYOsS1qvZ484Y9o',
    appId: '1:430784089707:web:919fddee1609299e472b2e',
    messagingSenderId: '430784089707',
    projectId: 'task-mgmt-1',
    authDomain: 'task-mgmt-1.firebaseapp.com',
    storageBucket: 'task-mgmt-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwmYBGqEVdHCK9bjXojKUTJmYuXn5wQDA',
    appId: '1:430784089707:android:0f571a917ba4bc3d472b2e',
    messagingSenderId: '430784089707',
    projectId: 'task-mgmt-1',
    storageBucket: 'task-mgmt-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWO3DflGbFtS7348K0jf1JHRZwZQVAEYA',
    appId: '1:430784089707:ios:9265f6398c0f75c5472b2e',
    messagingSenderId: '430784089707',
    projectId: 'task-mgmt-1',
    storageBucket: 'task-mgmt-1.appspot.com',
    iosClientId: '430784089707-s0tnchemqbsb8uj6kj65vhfte3d50nl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskMgmt',
  );
}
